# Generated by Django 4.2.22 on 2025-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the note (required).', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Plain text content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the note was last updated.')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
