# Generated by Django 4.2.22 on 2025-06-09 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user'], name='notes_app_n_user_id_50531e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='notes_app_n_created_1d9e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'created_at'], name='notes_app_n_user_id_327a64_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='notes_app_n_title_5740a4_idx'),
        ),
    ]
